# fly.toml app configuration file generated for pigment-api on 2023-04-20T13:30:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pigment-api"
primary_region = "dfw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "35s"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
